# MT SOFTWARE
version: '3'
services:
  db:
    container_name: postgres11
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./database:/mnt/dump
    restart: always


  # odoo12:
  #   container_name: odoo12
  #   image: odoo:12.0
  #   depends_on:
  #     - db
  #   ports:
  #     - "8012:8069"
  #   tty: true
  #   command: -- --dev=reload
  #   volumes:
  #     - ./o_12addons:/mnt/extra-addons
  #     - ./o_12lib:/var/lib/odoo
  #     - ./o_12odoo:/etc/odoo
  #     - ./o_12enterprice:/mnt/enterprice
  #   restart: always


#   odoo13:
#     container_name: odoo13
#     image: odoo:13.0
#     depends_on:
#       - db
#     ports:
#       - "8013:8069"
#     tty: true
#     command: -- --dev=reload
#     volumes:
#       - ./o_13addons:/mnt/extra-addons
#       - ./o_13lib:/var/lib/odoo
#       - ./o_13odoo:/etc/odoo
#       - ./o_13enterprice:/mnt/enterprice
#     restart: always

  # odoo14:
  #   container_name: odoo14
  #   image: odoo:14.0
  #   depends_on:
  #     - db
  #   ports:
  #     - "8014:8069"
  #   tty: true
  #   command: -- --dev=reload
  #   volumes:
  #     - ./o_14addons:/mnt/extra-addons
  #     - ./o_14lib:/var/lib/odoo
  #     - ./o_14odoo:/etc/odoo
  #     - ./o_14enterprice:/mnt/enterprice
  #   restart: always


  odoo15:
    container_name: odoo15
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8015:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./o_15addons:/mnt/extra-addons
      - ./o_15lib:/var/lib/odoo
      - ./o_15odoo:/etc/odoo
      - ./o_15enterprice:/mnt/enterprice
    restart: always

  pgadmin:
    image: thajeztah/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - 5050:5050
    volumes:
      - ./pgadmin:/pgadmin
    restart: always